export const mentorsData = [
    {
        mentorId: "1098291",
        avatar: "/avatarIcon.png",
        name: "Александр Петров",
        rating: 4.8,
        status: "Эксперт",
        category: "Программирование",
        skills: ["JavaScript", "React", "Node.js"],
        description: "Senior разработчик с 7-летним опытом в веб-разработке.",
        students: 15,
        bio: "Я работаю в сфере веб-разработки более 7 лет. За это время я участвовал в разработке крупных корпоративных приложений, а также создавал проекты с нуля. Владею JavaScript, React, Node.js и TypeScript. Обучил более 15 студентов, которые теперь работают в ведущих IT-компаниях.",
        experience: "7 лет работы в веб-разработке. Опыт работы в крупных IT-компаниях и стартапах.",
        education: "Высшее образование, Московский государственный университет, факультет прикладной математики и информатики.",
        contact: "email: alexpetrov@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "198223",
        avatar: "/avatarIcon.png",
        name: "Екатерина Иванова",
        rating: 4.5,
        status: "Выпускник",
        category: "Дизайн",
        skills: ["UI/UX", "Figma", "Photoshop"],
        description: "UX/UI дизайнер с опытом работы в крупных компаниях.",
        students: 8,
        bio: "Работаю в сфере дизайна уже 5 лет. Занимаюсь созданием интуитивно понятных пользовательских интерфейсов. Разрабатывала проекты для крупных компаний и стартапов. Хорошо владею Figma, Photoshop и понимаю основы front-end разработки.",
        experience: "5 лет работы в UX/UI дизайне. Проекты для крупных компаний и стартапов.",
        education: "Высшее образование, СПбГУ, факультет дизайна и мультимедиа.",
        contact: "email: katyaivanova@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "301234",
        avatar: "/avatarIcon.png",
        name: "Иван Сидоров",
        rating: 4.7,
        status: "Эксперт",
        category: "Программирование",
        skills: ["Python", "Django", "Flask"],
        description: "Backend разработчик с опытом разработки микросервисов.",
        students: 12,
        bio: "Специализируюсь на разработке серверной части приложений, имею опыт работы с Django и Flask. Участвовал в создании распределенных систем и микросервисной архитектуре.",
        experience: "6 лет работы в backend-разработке.",
        education: "Высшее образование, МФТИ, факультет прикладной математики.",
        contact: "email: ivansidorov@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "402345",
        avatar: "/avatarIcon.png",
        name: "Мария Смирнова",
        rating: 4.6,
        status: "Эксперт",
        category: "Data Science",
        skills: ["Python", "Machine Learning", "Pandas"],
        description: "Специалист по анализу данных и машинному обучению.",
        students: 10,
        bio: "Работаю в области Data Science последние 5 лет. Занимаюсь построением моделей машинного обучения и анализом больших данных.",
        experience: "5 лет в области Data Science.",
        education: "Высшее образование, ВШЭ, факультет прикладной математики.",
        contact: "email: mariasmirnova@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "503456",
        avatar: "/avatarIcon.png",
        name: "Дмитрий Кузнецов",
        rating: 4.9,
        status: "Эксперт",
        category: "DevOps",
        skills: ["Docker", "Kubernetes", "CI/CD"],
        description: "Специалист по автоматизации процессов разработки и развертывания.",
        students: 18,
        bio: "Имею глубокие знания в области DevOps. Оптимизировал процессы разработки и автоматизировал CI/CD пайплайны в крупных компаниях.",
        experience: "8 лет работы в DevOps.",
        education: "Высшее образование, МГУ, факультет вычислительной математики.",
        contact: "email: dmitrykuznetsov@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "604567",
        avatar: "/avatarIcon.png",
        name: "Анна Попова",
        rating: 4.4,
        status: "Выпускник",
        category: "UI/UX",
        skills: ["Sketch", "Figma", "Illustrator"],
        description: "Дизайнер пользовательских интерфейсов с креативным подходом.",
        students: 9,
        bio: "Работаю в сфере UI/UX дизайна уже 4 года. Создаю понятные и привлекательные интерфейсы для мобильных и веб-приложений.",
        experience: "4 года в UI/UX дизайне.",
        education: "Высшее образование, РХТУ, факультет дизайна.",
        contact: "email: annapopova@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "705678",
        avatar: "/avatarIcon.png",
        name: "Сергей Волков",
        rating: 4.3,
        status: "Эксперт",
        category: "Cybersecurity",
        skills: ["Penetration Testing", "Network Security", "Cryptography"],
        description: "Эксперт по информационной безопасности и защите данных.",
        students: 11,
        bio: "Специализируюсь на тестировании безопасности и защите сетей. Имею опыт проведения аудитов информационной безопасности в крупных организациях.",
        experience: "7 лет в области информационной безопасности.",
        education: "Высшее образование, Физтех, факультет безопасности информационных систем.",
        contact: "email: sergeyvolkov@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "806789",
        avatar: "/avatarIcon.png",
        name: "Ольга Романова",
        rating: 4.7,
        status: "Эксперт",
        category: "Программирование",
        skills: ["Java", "Spring Boot", "Microservices"],
        description: "Опытный Java-разработчик с глубокими знаниями Spring Boot.",
        students: 14,
        bio: "Работаю с Java более 8 лет, разрабатывал масштабируемые микросервисные архитектуры для крупных корпоративных проектов.",
        experience: "8 лет работы с Java.",
        education: "Высшее образование, МГУ, факультет прикладной математики и информатики.",
        contact: "email: olgaromanova@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "907890",
        avatar: "/avatarIcon.png",
        name: "Николай Жуков",
        rating: 4.5,
        status: "Выпускник",
        category: "Product Management",
        skills: ["Agile", "Scrum", "Roadmapping"],
        description: "Специалист по управлению продуктами и agile-методологиям.",
        students: 7,
        bio: "Опыт работы в продуктовом менеджменте позволяет мне помогать компаниям правильно структурировать процесс разработки и вывода продукта на рынок.",
        experience: "5 лет работы в Product Management.",
        education: "Высшее образование, СПбГУ, факультет экономики и управления.",
        contact: "email: nikolayzhukov@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "1001234",
        avatar: "/avatarIcon.png",
        name: "Виктория Лебедева",
        rating: 4.8,
        status: "Эксперт",
        category: "Дизайн",
        skills: ["UI/UX", "Adobe XD", "Illustrator"],
        description: "Креативный дизайнер с акцентом на пользовательский опыт.",
        students: 13,
        bio: "Создаю современные и интуитивные интерфейсы, работаю с лучшими инструментами для дизайна. Помогаю компаниям улучшить их визуальное представление.",
        experience: "6 лет в UI/UX дизайне.",
        education: "Высшее образование, РГКИ, факультет дизайна.",
        contact: "email: viktorialebedeva@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "1102345",
        avatar: "/avatarIcon.png",
        name: "Андрей Федоров",
        rating: 4.2,
        status: "Выпускник",
        category: "Blockchain",
        skills: ["Solidity", "Ethereum", "Smart Contracts"],
        description: "Блокчейн-разработчик с практическим опытом создания смарт-контрактов.",
        students: 10,
        bio: "Работаю с технологиями блокчейна более 3 лет, участвовал в разработке нескольких проектов на Ethereum.",
        experience: "3 года работы в области блокчейн-технологий.",
        education: "Высшее образование, МФТИ, факультет прикладной математики.",
        contact: "email: andreyfedorov@example.com",
        telegram: "https://t.me/Dinexio"
    },
    {
        mentorId: "1203456",
        avatar: "/avatarIcon.png",
        name: "Елена Николаева",
        rating: 4.6,
        status: "Эксперт",
        category: "AI/ML",
        skills: ["TensorFlow", "PyTorch", "Deep Learning"],
        description: "Специалист по искусственному интеллекту и глубокому обучению.",
        students: 16,
        bio: "Имею опыт разработки и внедрения нейронных сетей для анализа данных и решения сложных задач в области AI.",
        experience: "7 лет работы в сфере AI/ML.",
        education: "Высшее образование, МГУ, факультет вычислительной математики и кибернетики.",
        contact: "email: elenanikolaeva@example.com",
        telegram: "https://t.me/Dinexio"
    }
];
